DCOS-43591: Add DCOS_SERVICE_NAME to a whitelist for DC/OS tasks.
dcos/telegraf pull request #25
Opened 2018-10-15 13:36 UTC by elezar

This allows a consistent way to deal with multiple tasks from the same
framework.

I'll be happy to add the requirements bellow, but have not had a chance to do so.

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2018-10-15 16:58 UTC, janisz reviewed
Do we have a test for it?

2018-10-16 10:54 UTC, elezar commented
> Do we have a test for it?

Not yet. I haven't had a chance to get the dev environment started. Will do so as soon as I get a chance.

2018-10-16 14:26 UTC, janisz requested changes

2018-10-16 14:26 UTC, janisz commented on plugins/processors/dcos_metadata/dcos_metadata.go
>  	if labels != nil {
How about reverting this condition. This will simplify below code
```golang
if labels == nil {
   return results
}
```

2018-10-16 14:26 UTC, janisz commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +			selected = false
Do we need to set this variable with every iteration?

2018-10-16 14:26 UTC, janisz commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +				for _, whitelistLabel := range dcosMetricsLabelsWhitelist {
I don't understand this logic. If `k` is not empty string `selected = true`. Why do we need whitelist? It will only change `selected` to `true` if `k` is empty but an empty string is not whitelisted.

2018-10-19 00:36 UTC, branden commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +dcosMetricsLabelsWhitelist := [...]string{"DCOS_SERVICE_NAME"}
Would it make sense to retrieve these values from the plugin's config, rather than hardcoding them?

2018-10-23 00:42 UTC, elezar commented
I am going to close this PR as I don't have time to add the relevant tests myself.

2018-10-23 00:42 UTC, closed without merging