DCOS_OSS-4181: Cache executor containers
dcos/telegraf pull request #28
Opened 2018-10-24 22:51 UTC by gracedo

https://jira.mesosphere.com/browse/DCOS_OSS-4181
This caches executor containers, which are pulled from a task's parent container id. This will avoid repeated Mesos requests on constant cache misses.

2018-10-24 23:23 UTC, philipnrmn requested changes

2018-10-24 23:23 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +				return "", cid.GetValue()
I think it'd be conceptually neater to return the container ID first and its parent second...

2018-10-24 23:23 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// return its parent container ID if possible, along with its ID.
This comment's been rewritten a few times and I'm not sure it's more help than harm now. Can we clear it up, eg:

```suggestion
// getContainerIDs retrieves the container ID and the parent container ID of a                                          
// task from its TaskStatus. The container ID corresponds to the task's                                                 
// container, the parent container ID corresponds to the task's executor's                                              
// container. 
```

2018-10-24 23:23 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata_test.go
> +		assert.Equal(t, expected, dm.containers)
:+1:

2018-10-24 23:26 UTC, gracedo commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// return its parent container ID if possible, along with its ID.
excellent use of the new github feature! now let's see if this works..

2018-10-24 23:27 UTC, gracedo commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// return its parent container ID if possible, along with its ID.
![image](https://user-images.githubusercontent.com/5897740/47467166-b3282e80-d7a9-11e8-8941-4b2f379ccd8d.png)

2018-10-25 00:01 UTC, philipnrmn requested changes

2018-10-25 00:01 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// one-to-one mapping between tasks and containers; however it is
```suggestion
```

2018-10-25 00:01 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// getContainerIDs retrieves the parent container ID (if existent) and the
```suggestion
```

2018-10-25 00:01 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// container ID linked to this task. Task can have multiple statuses.
```suggestion
```

2018-10-25 00:01 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +// Each status can have multiple container IDs. In DC/OS, there is a
```suggestion
```

2018-10-25 00:01 UTC, philipnrmn commented on plugins/processors/dcos_metadata/dcos_metadata.go
>  // possible to have nested containers. Therefore we use the first status, and
```suggestion
```

2018-10-25 00:05 UTC, philipnrmn submitted a review, later dismissed
LGTM!

2018-10-25 00:59 UTC, branden submitted a review, later dismissed

2018-10-25 12:32 UTC, janisz submitted a review, later dismissed

2018-10-25 12:32 UTC, janisz commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +		for cid := range unknown {
Not relevant for this commit but it looks weird for me to range for the unknown in order to get some data.

2018-10-25 12:32 UTC, janisz commented on plugins/processors/dcos_metadata/dcos_metadata.go
> +func getContainerIDs(statuses []mesos.TaskStatus) (string, string) {
when `pcid` could be empty?

I like named return variable. It's got quick info what is returned. `string, string` means nothing for me. I'd prefer to alias it with something more meaningful.
```suggestion
func getContainerIDs(statuses []mesos.TaskStatus) (containerID string, parentContainerID string) {
```

2018-10-25 20:41 UTC, gracedo commented
@philipnrmn @branden @janisz can I get some more reviews after the last round of changes please, thanks! 😄

2018-10-26 13:48 UTC, janisz approved these changes

2018-10-26 14:27 UTC, philipnrmn approved these changes

2018-10-26 16:18 UTC, merged